---
deployment:
  tasks:
    - /bin/cp -R * $HOME/public_html/
    - /bin/cp -R .htaccess $HOME/public_html/ 2>/dev/null || true
    - /bin/cp -R robots.txt $HOME/public_html/ 2>/dev/null || true
    - /bin/chmod 755 $HOME/public_html/
    - /bin/chmod 644 $HOME/public_html/*.html 2>/dev/null || true
    - /bin/chmod 644 $HOME/public_html/*.php 2>/dev/null || true
    - /bin/chmod 755 $HOME/public_html/assets 2>/dev/null || true
    - /bin/chmod 755 $HOME/public_html/assets/php 2>/dev/null || true
    - /bin/chmod 644 $HOME/public_html/assets/php/*.php 2>/dev/null || true
    - /bin/chmod 755 $HOME/public_html/cities 2>/dev/null || true
    - /bin/chmod 644 $HOME/public_html/cities/*.html 2>/dev/null || true
    - /bin/touch $HOME/public_html/search_tracking.json
    - /bin/chmod 666 $HOME/public_html/search_tracking.json

